config/routes.rb
Ans::Application.routes.draw do
  get 'tags/:tag', to: 'questions#index', as: :tag 
  get "questions/search"
  get "users/show"
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :activities, only: :index
  resources :users
  resources :questions do 
     resources :answers do
        member do
          put "like", to: "answers#upvote"
          put "dislike", to: "answers#downvote"
        end
      end
  end
devise_scope :user do
     get "profile", to: "registrations#show"
end
root to: 'questions#search'
end

app/models/question.rb
class Question < ActiveRecord::Base
 # include PublicActivity::Model
  #tracked owner: ->(controller, model) {controller && controller.current_user}

  has_attached_file :qstnimg, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :qstnimg, :content_type => /\Aimage/

  has_many :answers, dependent: :destroy
  belongs_to :user
  validates_presence_of :user, :name, :description, :category, :tag_list
  validates_length_of :name, :description, :minimum =>10

  validates_presence_of :course,:year, :testname, :qno, :if => lambda {category == "Exam Question"}
  
  acts_as_taggable

  def self.search(params)
    # puts "========\n\n\n#{search}\n\n\n"

    name = params[:question][:name]
    category = params[:question][:category]
    course = params[:question][:course]
    testname = params[:question][:course]
    where("name like ? AND category like ? AND course like ? AND testname like ?", "%#{name}%", "%#{category}%", "%#{course}%", "%#{testname}") 
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
before_action :authenticate_user!, :except => [:show, :index, :search]
load_and_authorize_resource except: :show
  def index
      if params[:question]
          @questions = Question.search(params).order("created_at DESC") 
      else
          @questions = Question.all
      end
      if params[:tag]
        @questions = Question.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 10)
      else
        @questions = Question.paginate(:page => params[:page], :per_page => 10)
      end
  end

  def new 
    @question = Question.new
  end

  def create
    @question = Question.create(question_params)
    @question.user = current_user
    if @question.save
      redirect_to :questions => :index
    else
      render 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
     @question.user = current_user
    @question.assign_attributes(question_params)
    if @question.save
      redirect_to @question
    end
  end

def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      redirect_to questions_url
    end
end

def show
   @question = Question.find(params[:id])
end

def search
   if params[:question]
    redirect_to questions_url
  end
end


  private
def question_params
    params.require(:question).permit(:name, :description, :qstnimg, :category, :course, :year, :testname, :qno, :subpart, :tag_list)
end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_displayquestions.html.erb
 <% @questions.each do |question| %>
 <strong>Posted by: <%= link_to "#{question.user.first_name + ' ' + question.user.last_name}", question.user %></strong><br/>
 <% if question.category == "Exam Question" %>
       <strong class="caps"> 
        <%= "#{question.category}"%><span class="glyphicon glyphicon glyphicon-chevron-right"></span>
         <%= "#{question.course}" %><span class="glyphicon glyphicon glyphicon-chevron-right"></span>
          <%="#{question.year}"%> <span class="glyphicon glyphicon glyphicon-chevron-right"></span>
          <%="#{question.testname}"%> <span class="glyphicon glyphicon glyphicon-chevron-right"></span>
          <%="#{question.qno}" " ." "#{question.subpart}"%><br/>
     <% end %> </strong>
   <strong>Question: </strong> <%= question.name %><br/>
   <strong>Description:</strong> <%= question.description %><br/>
   <strong>Tags: </strong><%= raw question.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %><br/>
    <% if question.category != "Exam Question" %>
   <strong> Category: </strong><%= "#{question.category}"%><br/> 
   <% end %>
       
     <%= link_to 'Show Answers', question_path(question) %><br/>
        <% if can? :update, question %>
      <%= link_to 'Edit', edit_question_path(question) %>
      <% end %>
      <% if can? :destroy, question %>
      <%= link_to 'Delete', question_path(question),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      <hr/>
<br/>
<% end %>

app/views/questions/_form.html.erb
<%= javascript_include_tag "jquery-ui.min" %>
<script type="text/javascript">
$(document).ready(function() {
  $("#coursed,#yeard,#testnamed,#qnod,#checkbox,#subpart").hide();
  $("#category").change(function() {
      if ($( "#category option:selected" ).text()=="Exam Question")
      {
        $("#coursed,#yeard,#testnamed,#qnod,#checkbox").show();

            $('#ischecked').click(function() {
              if($(this).is(':checked'))
               {
                  $("#subpart").show();
              }
            });
             $('#no').click(function() {
              if($(this).is(':checked'))
               {
                  $("#subpart").hide();
              }
            });
      }
      if ($( "#category option:selected" ).text()!="Exam Question")
      {
        $("#coursed,#yeard,#testnamed,#qnod,#checkbox,#subpart").hide();
      }

  })
  
   
});
</script>
<%= javascript_include_tag "courselist" %>
    <%= stylesheet_link_tag "jquery-ui" %>
<style type="text/css">
#coursed,#yeard,#testnamed,#qnod, #checkbox, #subpart {
  margin-top:2%;
}
</style>
<div class="col-md-7">
<%= form_for @question,:html => { :multipart => true } do |f| %>
  <strong>Question:</strong><%= f.text_area :name , class: "form-control"%><br/>
  <strong>Question Description:</strong> <%= f.text_area :description, class: "form-control" %><br/>
  <strong>Add image:</strong> <%= f.file_field :qstnimg %><br/>
  <strong>Tags (separated by commas):</strong><%= f.text_field :tag_list %><br/>

  <strong>Category: </strong><select name="question[category]" id="category">
  <option></option>
  <option>Exam Question</option>
  <option>General</option>
  <option>Frosh Year Question</option>
  <option>Summer Opportunities/Job Hunting</option>
  </select><br/>

  
<div class="ui-widget" id="coursed">
  <strong>Course: </strong>
  <input id="tags" name="question[course]">
</div>
 
<div id="yeard">
   <strong>Year: </strong><select name="question[year]" >
   <option></option>
   <%  (1..14).each do |count| %>
    <% if count<10 %>
      <option>200<%= count %></option>
    <% else %>
      <option>20<%= count %></option>
    <% end %>
   <% end %>
  </select><br/>
</div>

<div id="testnamed">
   <strong>Test Name: </strong><select name="question[testname]" >
   <option></option>
   <option>Final Exam</option>
   <option>Midterm</option>
   <option>Quiz</option>
   <option>Assignment</option>
   <option>Other</option>
  </select><br/>
</div>

<div id="qnod">
   <strong>Question Number: </strong><select name="question[qno]">
   <option></option>
     <%  (1..20).each do |count| %>
   <option><%= count %></option>
   <% end %>
  </select><br/> 
</div>

<div id="checkbox">
 <strong> Are you asking about particular subpart? </strong>
  <input type="radio" name="question[subpartcheckbox]" id="ischecked" value="yes">Yes 
  <input type="radio" name="question[subpartcheckbox]" id="no" value="no">No<br/>
</div>

<div id="subpart">
   <strong>Subpart character: </strong><select name="question[subpart]">
   <%  (1..20).each do |count| %>
    <option><%= count %></option>
   <% end %>
  </select><br/> 
</div>

<br/><br/>
  <%= f.submit "Ask Question", class: "btn btn-default"%>
<%end%>
</div>

app/views/questions/_search.html.erb
<%= javascript_include_tag "jquery-ui.min" %>
<%= stylesheet_link_tag "searchhome" %>
  <script type="text/javascript">
$(document).ready(function() {
  $("#show").hide();
  $("#category").change(function() {
      if ($( "#category option:selected" ).text()=="Exam Question")
      {
        $("#show").show();
        $( "select[name='question[course]']").prop('disabled', false);
         $("select[name='question[year]']").prop('disabled', false);
          $("select[name='question[testname]']").prop('disabled', false);
           $("select[name='question[qno]']").prop('disabled', false);

          
      }
      if ($( "#category option:selected" ).text()!="Exam Question")
      {
        $("#show").hide();
        $( "select[name='question[course]']").prop('disabled', true);
         $("select[name='question[year]']").prop('disabled', true);
          $("select[name='question[testname]']").prop('disabled', true);
           $("select[name='question[qno]']").prop('disabled', true);
      }


  })
   
});
</script>
<%= javascript_include_tag "courselist" %>
<%= stylesheet_link_tag "jquery-ui" %>
<div id="mainform">
  <br/><br/>
<%= form_tag(questions_path, :method => "get", id: "search-form", class: "navbar-form navbar-left", role: "search", name: "qform") do %>
  <div class="form-group">
    <input type="text" name="question[name]" class="form-control" placeholder = "Search Questions" id="searchtext"/><br/>
  </div>

  <div class="form-group" id="select">
    <select name="question[category]" id="category" class="form-control">
      <option>All</option>
      <option>Exam Question</option>
      <option>General</option>
      <option>Frosh Year Question</option>
      <option>Summer Opportunities/Job Hunting</option>
    </select>
  </div><br/><br/>
<div id="show">
   <div class="ui-widget form-group" id="course">
  <input id="tags" class="form-control tags" name="question[course]" placeholder="Select Course">
</div>
 
<div id="year" class="form-group">
   <select name="question[year]" class="form-control" id="selectsize">
   <option><strong>Year:</strong></option>
   <%  (1..14).each do |count| %>
    <% if count<10 %>
      <option>200<%= count %></option>
    <% else %>
      <option>20<%= count %></option>
    <% end %>
   <% end %>
  </select>
</div>

<div id="testname" class="form-group">
   <select name="question[testname]" class="form-control" id="selectsize">
   <option><strong>Test Name:</strong></option>
   <option>Final Exam</option>
   <option>Midterm</option>
   <option>Quiz</option>
   <option>Assignment</option>
   <option>Other</option>
  </select>
</div>
<br/><br/>
</div>
  <%= submit_tag "Search", :name => nil, class: "btn btn-default", id: "searchbox" %> 
<% end %>
  
</div> <!-- search -->

app/views/questions/_searchrest.html.erb
<%= javascript_include_tag "jquery-ui.min" %>
<%= stylesheet_link_tag "index" %>
  <script type="text/javascript">
$(document).ready(function() {
  $("#show").hide();
  $("#categorys").change(function() {
      if ($( "#categorys option:selected" ).text()=="Exam Question")
      {
        $("#show").show();
        $( "select[name='question[course]']").prop('disabled', false);
         $("select[name='question[year]']").prop('disabled', false);
          $("select[name='question[testname]']").prop('disabled', false);
           $("select[name='question[qno]']").prop('disabled', false);

          
      }
      if ($( "#categorys option:selected" ).text()!="Exam Question")
      {
        $("#show").hide();
        $( "select[name='question[course]']").prop('disabled', true);
         $("select[name='question[year]']").prop('disabled', true);
          $("select[name='question[testname]']").prop('disabled', true);
           $("select[name='question[qno]']").prop('disabled', true);
      }


  })
   
});
</script>
<%= javascript_include_tag "courselist" %>
<%= stylesheet_link_tag "jquery-ui" %>
<div id="mainforms">
  <br/><br/>
<%= form_tag(questions_path, :method => "get", id: "search-form", class: "navbar-form navbar-left", role: "search", name: "qform") do %>
  <div class="form-group">
    <input type="text" name="question[name]" class="form-control" placeholder = "Search Questions" id="searchtext"/><br/>
  </div>

  <div class="form-group" id="selects">
    <select name="question[category]" id="categorys" class="form-control">
      <option>All</option>
      <option>Exam Question</option>
      <option>General</option>
      <option>Frosh Year Question</option>
      <option>Summer Opportunities/Job Hunting</option>
    </select>
  </div><br/><br/>
<div id="show">
   <div class="ui-widget form-group" id="courses">
  <input id="tags" class="form-control" name="question[course]" placeholder="Select Course">
</div><br/>
<div id="testnames" class="form-group">
   <select name="question[testname]" class="form-control" id="selectsizes">
   <option><strong>Test Name:</strong></option>
   <option>Final Exam</option>
   <option>Midterm</option>
   <option>Quiz</option>
   <option>Assignment</option>
   <option>Other</option>
  </select>
</div><br/>

<div id="years" class="form-group">
   <select name="question[year]" class="form-control" id="selectsizes">
   <option><strong>Year:</strong></option>
   <%  (1..14).each do |count| %>
    <% if count<10 %>
      <option>200<%= count %></option>
    <% else %>
      <option>20<%= count %></option>
    <% end %>
   <% end %>
  </select>
  <br/><br/>
</div>
</div>


  <%= submit_tag "Search", :name => nil, class: "btn btn-default", id: "searchboxs" %> 
<% end %>
  
</div> <!-- search -->

app/views/questions/_tagcloud.html.erb
<%= javascript_include_tag "jquery-ui.min" %>
<%= stylesheet_link_tag "index" %>
<div id = "tag_cloud">
  Filter by tag:<br/>
  <% tag_cloud Question.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="center">
<h1>Edit question</h1>
<%= render 'form' %>
</div>

app/views/questions/index.html.erb

<div class="col-md-4">
  <%= render 'tagcloud' %>
  <%= render 'searchrest' %>
</div>
<% if params[:question] %>
  <div class="col-md-8">
  <h1><strong>Search Results</strong></h1><br/><br/>
  <% if @questions.present? %>
    <%= render 'displayquestions' %>
  <%else%>
    No results found!
  <% end %>
  </div>
<% else %>
  <div class="col-md-7">
  <h1><strong>Recent Questions</strong></h1><br/><br/>
    
       <%= render 'displayquestions' %>

<%= will_paginate @questions %>
  </div>

<% end %>

app/views/questions/new.html.erb

<div class="col-md-4">
<%= render 'searchrest' %>
</div>

<div class="col-md-7">
<% if @question.errors.any? %>
<div class="alert alert-error">
   <a href="#" data-dismiss="alert" class="close">×</a>
  <% @question.errors.full_messages.each do |msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
  <% end %>
<% end %> 
</div>
<h1>New  Question</h1>
<%= render 'form' %>
</div>

app/views/questions/search.html.erb

<h1 id="heading"> answers</h1>
<%= render 'search' %>

app/views/questions/show.html.erb
<div class="col-md-4">
<%= render 'searchrest' %>
</div>

<div class="col-md-7">
<p>
  <strong>Posted by: <%= link_to @question.user.first_name + ' ' + @question.user.last_name, @question.user %></strong><br/>
 <% if @question.category == "Exam Question" %>
       <strong class="caps"> 
        <%= @question.category%><span class="glyphicon glyphicon glyphicon-chevron-right"></span>
         <%= @question.course %><span class="glyphicon glyphicon glyphicon-chevron-right"></span>
          <%=@question.year%> <span class="glyphicon glyphicon glyphicon-chevron-right"></span>
          <%=@question.testname%> <span class="glyphicon glyphicon glyphicon-chevron-right"></span>
          <%=@question.qno%>.<%= @question.subpart %><br/>

     <% end %> </strong>
   <strong>Question: </strong> <%= @question.name %><br/>
   <strong> Description:</strong> <%= @question.description %><br/>
   <% if @question.qstnimg.present? %>
    <%= image_tag @question.qstnimg.url(:medium) %>   <br/>
   <% end %>

    <% if @question.category != "Exam Question" %>
   <strong> Category: </strong><%= @question.category%><br/> 
   <% end %>
       
     <%= link_to 'Show Answers', question_path(@question) %><br/>
        <% if can? :update, @question %>
      <%= link_to 'Edit', edit_question_path(@question) %>
      <% end %>
      <% if can? :destroy, @question %>
      <%= link_to 'Delete', question_path(@question),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      <hr/>
<br/>
  
<h2><strong>Answers</strong></h2>
<% @question.answers.each do |answer| %>
<div class="answers">
  
  <p>
    <%= raw answer.body %>
  </p>
  <br/>
        <%#= pluralize answer.reputation_for(:votes).to_i, "vote" %>
    <%# if can? :vote, answer %>
      <%# if current_user && !current_user.voted_for?(answer) %>
        <%#= link_to "up", vote_question_answer_path(answer.question_id, answer, type: "up"), method: "post" %>
        <%#= link_to "down", vote_question_answer_path(answer.question_id, answer,  type: "down"), method: "post" %>
      <%# end %>
    <%# end %>
    Likes: <%= answer.get_upvotes.size %> |
    Dislikes: <%= answer.get_downvotes.size %><br/>
  <% if can? :upvote, answer %>
    <% if user_signed_in? %>
      <% if current_user.voted_for? answer %>
        <% if current_user.voted_as_when_voted_for answer %> 
          Liked 
          <%= link_to "Dislike", dislike_question_answer_path(answer.question_id, answer), method: :put %>
        <% else %>
            <%= link_to "Like", like_question_answer_path(answer.question_id, answer), method: :put %>
            Disliked
        <% end %>
      <% else %>
        <%= link_to "Like", like_question_answer_path(answer.question_id, answer), method: :put %>
        <%= link_to "Dislike", dislike_question_answer_path(answer.question_id, answer), method: :put %>
      <% end %>
    <% else %>
    <%= link_to('Sign up/Sign in to vote', new_user_session_path)  %> 
    <% end %>
  <% end %>
   <% if answer.user %>
   <div id="ansuser">
    <% if answer.user.avatar.exists? %>
    <%= image_tag answer.user.avatar.url(:thumb) %>
    <% else %>
     <%= image_tag asset_path('no-profile-image.jpg'), class: 'default-image' %>
    <% end %>
    <%= link_to "#{answer.user.first_name + ' ' + answer.user.last_name}", answer.user %>
    <strong>(<% if answer.user.score>0 %>
      <%= answer.user.score %>
      <% else %>
      <%= 0 %>
      <% end %>)</strong>
  </div>
    <% end %>
      <br/>
    <% if can? :destroy, answer %>
  <%= link_to 'Delete Answer', [answer.question, answer],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
    <% end %>
</p>
</div>
<% end %>
<h2>Add an answer:</h2>
<%= form_for([@question, @question.answers.build]) do |f| %>
  <!--<p>
    <%#= f.label :name %><br>
    <%#= f.text_field :name %>
  </p> -->
  <p>
    <%#= f.label :Answer %><br>
    <%#= f.text_area :body %>

    <%= f.text_area :body, id: "some-textarea", :class => "tinymce", :rows => 15, :cols => 40 %>
<%= tinymce %>
  </p>
  <p>
    <%= f.submit 'Answer', class: 'btn btn-large' %>
  </p>
<% end %>


</div>