config/routes.rb
Ans::Application.routes.draw do
  get 'tags/:tag', to: 'questions#index', as: :tag 
  get "questions/search"
  get "users/show"
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :activities, only: :index
  resources :users
  resources :questions do 
     resources :answers do
        member do
          put "like", to: "answers#upvote"
          put "dislike", to: "answers#downvote"
        end
      end
  end
devise_scope :user do
     get "profile", to: "registrations#show"
end
root to: 'questions#search'
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = PublicActivity::Activity.order("created_at desc").where(recipient_id: current_user, owner_type: "User")
    @myacts = PublicActivity::Activity.order("created_at desc").where(owner_id: current_user, owner_type: "User")
  end

  #def destroy
   # @activity = PublicActivity::Activity.find(params[:id])
   # if @activity.destroy
    #  redirect_to activities_url
    #end
  #end 
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/index.html.erb
<div class="center">
<h1>Notifications</h1>
<% if @activities.present? %>
<% @activities.each do |activity| %>
  <div class="activity">
    <%= link_to activity.owner.first_name, activity.owner if activity.owner %>
    added an answer to
    <% if activity.trackable %>
    <%#= activity.inspect %>
    <%= link_to activity.trackable.question.name, activity.trackable.question %>
    <br/><br/>
       <%#= link_to 'Delete', activity_path(activity),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
<% end %>

<% end %>
<!--
<h1>Questions I have answered</h1>
<% if @myacts.present? %>
<% @myacts.each do |myact| %>
  <div class="activity">
    <%= link_to myact.owner.first_name, myact.owner if myact.owner %>
    added an answer to
    <% if myact.trackable %>
    <%#= activity.inspect %>
    <%= link_to myact.trackable.question.name, myact.trackable.question %>
    <br/><br/>
       <%#= link_to 'Delete', activity_path(activity),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
<% end %>

<% end %>
</div>
-->