config/routes.rb
Ans::Application.routes.draw do
  get 'tags/:tag', to: 'questions#index', as: :tag 
  get "questions/search"
  get "users/show"
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :activities, only: :index
  resources :users
  resources :questions do 
     resources :answers do
        member do
          put "like", to: "answers#upvote"
          put "dislike", to: "answers#downvote"
        end
      end
  end
devise_scope :user do
     get "profile", to: "registrations#show"
end
root to: 'questions#search'
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Ans</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <link href='http://fonts.googleapis.com/css?family=Rajdhani' rel='stylesheet' type='text/css'>
  <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
    </script>-->
  <%= csrf_meta_tags %>
</head>
<body>
  
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'UofTanswers', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      

      <ul class="nav navbar-nav navbar-right">
        <%= link_to 'New Question', new_question_path ,class: 'btn-custom' %>
        <li><%= link_to 'Recent Questions', questions_path %></li>
       <% if user_signed_in? %>
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, <%= current_user.first_name %> <span class="badge"><%#= current_user.reputation_for(:votes).to_i %></span><span class="caret"> </span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'View Profile', current_user %></li>
            <li class="divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
       <li><%= link_to 'Notifications', activities_path %></li>
        <% else %>
        <li> <%= link_to('Sign up/Sign in', new_user_session_path)  %>  </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>
<div class="center">
<%= render 'layouts/messages' %>.
</div>
<%= yield %>

</body>
</html>